# Generated by Django 5.0.1 on 2024-04-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('vegetarian', models.BooleanField()),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
