# Generated by Django 5.0.1 on 2024-04-21 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_fooditem_retaurant_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='retaurant_name',
            new_name='restaurent_name',
        ),
    ]
