# Generated by Django 5.0.1 on 2024-04-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_restaurant_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisines',
            field=models.ManyToManyField(to='app1.cuisine'),
        ),
    ]
