# Generated by Django 5.0.1 on 2024-04-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_cuisine_restaurant_cuisines'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='location_url',
            field=models.URLField(null=True),
        ),
    ]
