# Generated by Django 5.0.1 on 2024-04-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_placed_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
