# Generated by Django 5.0.1 on 2024-04-26 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_order_order_placed_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fooditem',
        ),
    ]
